name = "server"
type = "webpack"

account_id = ""
route = ""
zone_id = ""

compatibility_date = "2022-01-22"
webpack_config = "webpack.config.js"
workers_dev = true

# Enable a kv-namespace to use the KV caching feature
#
# kv-namespaces = [
#   { binding = "WORKERS_GRAPHQL_CACHE", id = "" }
# ]

kv_namespaces = [
  {binding = "PASTE_DB", preview_id = "d7444e0687924555bacb2de504fde18c", id = "7580653883ec446c80281f258d63c724"},
  {binding = "KEY_DB", preview_id = "dca7f1b0e5154cd3a096bc006e192537", id = "67ba3c199e9543d98922faa353b6bfb3"},
]

[build]
command = "npm ci && npm run build"

[build.upload]
format = "modules"
main = "./src/index.js"

[dev]
ip = "0.0.0.0"
local_protocol = "http"
port = 8787
upstream_protocol = "https"
